/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.gradle.workshop

import org.gradle.api.Project
import org.gradle.api.Plugin

open class GreetingPluginExtension {
    var message = "Hello from GreetingPlugin"
}

private const val EXTENSION_NAME = "greetingConf"

class PluginPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        project.extensions.create(
            EXTENSION_NAME, GreetingPluginExtension::class.java
        )

        project.tasks.register("greeting") { task ->
            task.doLast {
                val pluginExtension = project.extensions.getByName(EXTENSION_NAME) as? GreetingPluginExtension
                println("Hello from plugin 'gradle.workshop.plugin.greeting' ${pluginExtension?.message}")
            }
        }
    }
}
