/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.gradle.workshop

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val unused = "test"
        val classUnderTest = App()
        assertNotNull(classUnderTest.showSomeColor(), "app should have a greeting")
    }
}
