/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.gradle.workshop
// Cannot import ! is not leaked to consumers
//import com.diogonunes.jcolor.Ansi.colorize
import org.apache.commons.math3.random.RandomDataGenerator



class App {
    fun showSomeColor(): String {
        val library = Library()
        val someNumber = RandomDataGenerator().nextInt(0, 255)
        return library.makeSomeColor() + "\n I can use random from math-commons $someNumber"
    }
}

fun main() {
    println(App().showSomeColor())
}
